<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class MasterproductSeeder extends Seeder
{
    public function run()
    {
        $data = [
            [
                'product_code' => '8093',
                'product_group' => '000001',
                'product_name' => 'AXIS',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'product_code' => '8075',
                'product_group' => '000002',
                'product_name' => 'BAG',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'product_code' => '8099',
                'product_group' => '000002',
                'product_name' => 'ALUMINIUM BAG',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'product_code' => '8015',
                'product_group' => '000003',
                'product_name' => 'BALL',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'product_code' => '8036',
                'product_group' => '000004',
                'product_name' => 'BEARING',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'product_code' => '8100',
                'product_group' => '000004',
                'product_name' => 'BALL BEARING',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'product_code' => '8008',
                'product_group' => '000005',
                'product_name' => 'BELT',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'product_code' => '8101',
                'product_group' => '000005',
                'product_name' => 'TIMING BELT',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'product_code' => '8018',
                'product_group' => '000006',
                'product_name' => 'BIT INSERT',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'product_code' => '8017',
                'product_group' => '000007',
                'product_name' => 'BOLT',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'product_code' => '8011',
                'product_group' => '000008',
                'product_name' => 'BUSH',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'product_code' => '8102',
                'product_group' => '000009',
                'product_name' => 'CABLE TIE',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'product_code' => '8021',
                'product_group' => '000009',
                'product_name' => 'CABLE TIE(BAND),LOCK',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'product_code' => '8028',
                'product_group' => '000010',
                'product_name' => 'CAM',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'product_code' => '8135',
                'product_group' => '000010',
                'product_name' => 'ADJUST CAM',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'product_code' => '8091',
                'product_group' => '000011',
                'product_name' => 'CLIP',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'product_code' => '8103',
                'product_group' => '000011',
                'product_name' => 'PLASTIC CLIP',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'product_code' => '8074',
                'product_group' => '000012',
                'product_name' => 'CORE CLUMP',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'product_code' => '8002',
                'product_group' => '000013',
                'product_name' => 'EYELET',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'product_code' => '8086',
                'product_group' => '000014',
                'product_name' => 'FAN GUARD',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'product_code' => '8037',
                'product_group' => '000015',
                'product_name' => 'FLANGE',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'product_code' => '8083',
                'product_group' => '000016',
                'product_name' => 'FLEX',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'product_code' => '8118',
                'product_group' => '000016',
                'product_name' => 'FLEXIBLE PRINTED CIRCUIT',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'product_code' => '8027',
                'product_group' => '000017',
                'product_name' => 'GEAR',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'product_code' => '8032',
                'product_group' => '000017',
                'product_name' => 'GEAR-P',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'product_code' => '8104',
                'product_group' => '000017',
                'product_name' => 'PLASTIC GEAR',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'product_code' => '8090',
                'product_group' => '000017',
                'product_name' => 'GEAR HOLDER',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'product_code' => '8085',
                'product_group' => '000018',
                'product_name' => 'GROMMET',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'product_code' => '8105',
                'product_group' => '000018',
                'product_name' => 'RUBBER GROMMET',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'product_code' => '8031',
                'product_group' => '000018',
                'product_name' => 'RUBBER',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'product_code' => '8121',
                'product_group' => '000018',
                'product_name' => 'O-RING',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'product_code' => '8122',
                'product_group' => '000018',
                'product_name' => 'CUSHION PACKING',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'product_code' => '8025',
                'product_group' => '000019',
                'product_name' => 'HOLDER',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'product_code' => '8038',
                'product_group' => '000020',
                'product_name' => 'LOCKING CIRCUIT',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'product_code' => '8026',
                'product_group' => '000021',
                'product_name' => 'MAGNET',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'product_code' => '8004',
                'product_group' => '000022',
                'product_name' => 'NUT',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'product_code' => '8029',
                'product_group' => '000022',
                'product_name' => 'insert NUT',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'product_code' => '8106',
                'product_group' => '000022',
                'product_name' => 'CAP NUT',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'product_code' => '8010',
                'product_group' => '000023',
                'product_name' => 'OILESS METAL',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'product_code' => '8107',
                'product_group' => '000023',
                'product_name' => 'OILESS',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'product_code' => '8003',
                'product_group' => '000024',
                'product_name' => 'PIN',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'product_code' => '8033',
                'product_group' => '000024',
                'product_name' => 'PIN-P',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'product_code' => '8108',
                'product_group' => '000024',
                'product_name' => 'PLASTIC PIN',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'product_code' => '8020',
                'product_group' => '000025',
                'product_name' => 'PINION',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'product_code' => '8034',
                'product_group' => '000026',
                'product_name' => 'PLASTIC FLIM',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'product_code' => '8012',
                'product_group' => '000027',
                'product_name' => 'PLATE',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'product_code' => '8109',
                'product_group' => '000027',
                'product_name' => 'METAL PLATE',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'product_code' => '8110',
                'product_group' => '000027',
                'product_name' => 'CONTACT PLATE',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'product_code' => '8030',
                'product_group' => '000028',
                'product_name' => 'POINTER',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'product_code' => '8001',
                'product_group' => '000029',
                'product_name' => 'RING',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'product_code' => '8072',
                'product_group' => '000029',
                'product_name' => 'RING-P',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'product_code' => '8111',
                'product_group' => '000029',
                'product_name' => 'PLASTIC RING',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'product_code' => '8088',
                'product_group' => '000030',
                'product_name' => 'RETAINER RING',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'product_code' => '8112',
                'product_group' => '000030',
                'product_name' => 'RETAINING RING',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'product_code' => '8014',
                'product_group' => '000031',
                'product_name' => 'RIVET',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'product_code' => '8005',
                'product_group' => '000032',
                'product_name' => 'SCREW',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'product_code' => '8113',
                'product_group' => '000032',
                'product_name' => 'MICRO SCREW',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'product_code' => '8006',
                'product_group' => '000033',
                'product_name' => 'SHAFT',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'product_code' => '8089',
                'product_group' => '000034',
                'product_name' => 'SHIM',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'product_code' => '8094',
                'product_group' => '000034',
                'product_name' => 'SPRING SHIM',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'product_code' => '8087',
                'product_group' => '000035',
                'product_name' => 'SNAP RING',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'product_code' => '8016',
                'product_group' => '000036',
                'product_name' => 'SPACER',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'product_code' => '8114',
                'product_group' => '000036',
                'product_name' => 'METAL SPACER',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'product_code' => '8115',
                'product_group' => '000036',
                'product_name' => 'PLASTIC SPACER',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'product_code' => '8013',
                'product_group' => '000037',
                'product_name' => 'SPRING,MICRO-SPRINGS',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'product_code' => '8095',
                'product_group' => '000038',
                'product_name' => 'SPRING PIN',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'product_code' => '8076',
                'product_group' => '000039',
                'product_name' => 'STRING',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'product_code' => '8007',
                'product_group' => '000040',
                'product_name' => 'STUD',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'product_code' => '8039',
                'product_group' => '000041',
                'product_name' => 'SUPPORTER',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'product_code' => '8019',
                'product_group' => '000042',
                'product_name' => 'TERMINAL',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'product_code' => '8009',
                'product_group' => '000043',
                'product_name' => 'WASHER',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'product_code' => '8035',
                'product_group' => '000043',
                'product_name' => 'WASHER-P',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'product_code' => '8116',
                'product_group' => '000043',
                'product_name' => 'PLASTIC WASHER',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'product_code' => '8073',
                'product_group' => '000044',
                'product_name' => 'WIRE HOLDER',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'product_code' => '8097',
                'product_group' => '000045',
                'product_name' => 'WRENCH',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'product_code' => '8096',
                'product_group' => '000046',
                'product_name' => 'CONNECTOR',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'product_code' => '8119',
                'product_group' => '000046',
                'product_name' => 'CONNECTOR SUB ASSY',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'product_code' => '8131',
                'product_group' => '000047',
                'product_name' => 'PLUG',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'product_code' => '8120',
                'product_group' => '000047',
                'product_name' => 'AIR PLUG',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'product_code' => '8124',
                'product_group' => '000048',
                'product_name' => 'ROLLER',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'product_code' => '8125',
                'product_group' => '000048',
                'product_name' => 'G-ROLLER',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'product_code' => '8127',
                'product_group' => '000048',
                'product_name' => 'SET,G-ROLLER',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'product_code' => '8126',
                'product_group' => '000049',
                'product_name' => 'PIPE',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'product_code' => '8062',
                'product_group' => '000050',
                'product_name' => 'TENSION PULLEY',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'product_code' => '8129',
                'product_group' => '000051',
                'product_name' => 'CUSHION',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'product_code' => '8128',
                'product_group' => '000052',
                'product_name' => 'COLLAR',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            
            // Add more sets of data as needed
        ];


        $this->db->table('mastertbt_product')->insertBatch($data);
    }
}
