<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class MastercustomerSeeder extends Seeder
{
    public function run()
    {
        $data = [
            [
                'customer_code' => 'BOI0147',
                'name_ic' => 'MARUYAMA MFG (THAILAND) CO.,LTD',
                'name_tbt' => 'MARUYAMA MFG (THAILAND) CO.,LTD.',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'customer_code' => 'BOI0044',
                'name_ic' => 'OKI DATA MANUFACTURING (THAILAND) CO.,LTD.',
                'name_tbt' => 'OKI DATA MANUFACTURING ( THAILAND ) CO.,LTD.',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'customer_code' => 'BOI0015',
                'name_ic' => 'NMB-MINEBEA THAI LIMITED',
                'name_tbt' => 'NMB-MINEBEA THAI LTD.',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'customer_code' => 'BOI0103',
                'name_ic' => 'MITSUI SIAM COMPONENTS COMPANY LIMITED',
                'name_tbt' => 'MITSUI SIAM COMPONENTS CO.,LTD. ',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'customer_code' => 'BOI0059',
                'name_ic' => 'NOBLE ELECTRONICS (THAILAND) CO.,LTD.',
                'name_tbt' => 'NOBLE ELECTRONICS (THAILAND) CO.,LTD.',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'customer_code' => 'BOI0146',
                'name_ic' => 'ITAK INTERNATIONAL (THAILAND) LIMITED',
                'name_tbt' => 'ITAK INTERNATIONAL (THAILAND) LTD.',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'customer_code' => 'BOI9001',
                'name_ic' => 'CASIO (THAILAND) COMPANY LIMITED',
                'name_tbt' => 'CASIO (THAILAND) CO.,LTD.',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'customer_code' => 'BOI0154',
                'name_ic' => 'KEW (THAILAND) LIMITED',
                'name_tbt' => 'KEW (THAILAND) LIMITED  ',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'customer_code' => 'BOI0153',
                'name_ic' => 'ROLAND DIGITAL GROUP (THAILAND) LIMITED',
                'name_tbt' => 'ROLAND DIGITAL GROUP (THAILAND) LIMITED.',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'customer_code' => 'BOI0077',
                'name_ic' => 'THAI SIIX COMPANY LIMITED',
                'name_tbt' => 'THAI SIIX CO., LTD.',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'customer_code' => 'BOI0151',
                'name_ic' => 'TOHOKU SOLUTIONS COMPANY LIMITED',
                'name_tbt' => 'TOHOKU SOLUTIONS CO., LTD.',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'customer_code' => 'BOI0183',
                'name_ic' => 'HUDSON MANUFACTURE (THAILAND) CO.,LTD.',
                'name_tbt' => 'HUDSON MANUFACTURE (THAILAND) CO.,LTD.',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'customer_code' => 'BOI0178',
                'name_ic' => 'ACME INDUSTRY COMPANY LIMITED',
                'name_tbt' => 'ACME INDUSTRY CO., LTD.',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'customer_code' => 'BOI0040',
                'name_ic' => 'MURAMOTO ELECTRON (THAILAND)PUBLIC COMPANY LIMITED',
                'name_tbt' => 'MURAMOTO ELECTRON(THAILAND)PUBLIC COMPANY LIMITED',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'customer_code' => 'BOI0087',
                'name_ic' => 'MURAMOTO ELECTRON (THAILAND)PUBLIC COMPANY LIMITED',
                'name_tbt' => 'MURAMOTO ELECTRON(THAILAND)PUBLIC COMPANY LIMITED',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'customer_code' => 'BOI0193',
                'name_ic' => 'K - TECH INDUSTRIAL (THAILAND ) CO., LTD.',
                'name_tbt' => 'K-TECH INDUSTRIAL (THAILAND) CO.,LTD.',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'customer_code' => 'BOI0162',
                'name_ic' => 'THAI FUJI PLASTICS COMPANY LIMITED',
                'name_tbt' => 'THAI FUJI PLASTICS CO.,LTD.',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'customer_code' => 'BOI0038',
                'name_ic' => 'SEIKO PRECISION (THAILAND) COMPANY LIMITED',
                'name_tbt' => 'SEIKO PRECISION (Thailand) Co.,Ltd.',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'customer_code' => 'BOI0095',
                'name_ic' => 'KATOLEC (THAILAND) COMPANY LIMITED',
                'name_tbt' => 'KATOLEC (THAILAND) CO.,LTD.  HEAD OFFICE',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'customer_code' => 'BOI0110',
                'name_ic' => 'HAKKO (THAILAND) COMPANY LIMITED',
                'name_tbt' => 'HAKKO (THAILAND) CO., LTD.',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'customer_code' => 'BOI0096',
                'name_ic' => 'ASIAN STANLEY INTERNATIONAL COMPANY LIMITED',
                'name_tbt' => 'ASIAN STANLEY INTERNATIONAL CO.,LTD.',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'customer_code' => 'BOI0079',
                'name_ic' => 'TENMA (THAILAND) COMPANY LIMITED',
                'name_tbt' => 'TENMA (THAILAND) CO.,LTD.',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'customer_code' => 'BOI0069',
                'name_ic' => 'YANO ELECTRONICS (THAILAND) LIMITED',
                'name_tbt' => 'YANO ELECTRONICS (THAILAND) LTD.',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'customer_code' => 'BOI0184',
                'name_ic' => 'ALPHA HOUSING HARDWARE (THAILAND) COMPANY LIMITED',
                'name_tbt' => 'ALPHA HOUSING HARDWARE (THAILAND)CO.,LTD.',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'customer_code' => 'BOI0204',
                'name_ic' => 'TAKANE ELECTRONICS (THAILAND) COMPANY LIMITED',
                'name_tbt' => 'TAKANE ELECTRONICS (THAILAND) CO., LTD.',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'customer_code' => 'BOI0001',
                'name_ic' => 'AIPHONE COMMUNICATIONS (THAILAND) CO.,LTD',
                'name_tbt' => 'AIPHONE COMMUNICATIONS(THAILAND) CO.,LTD.',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'customer_code' => 'BOI0173',
                'name_ic' => 'NIKON (THAILAND) COMPANY LIMITED',
                'name_tbt' => 'NIKON (THAILAND) CO., LTD.',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'customer_code' => 'BOI0156',
                'name_ic' => 'SHIBAKAWA (THAILAND) CO.,LTD',
                'name_tbt' => 'SHIBAKAWA (THAILAND) CO.,LTD.',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'customer_code' => 'BOI0045',
                'name_ic' => 'WALBRO (THAILAND) COMPANY LIMITED',
                'name_tbt' => 'WALBRO (THAILAND)CO.,LTD.',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'customer_code' => 'BOI0003',
                'name_ic' => 'JVCKENWOOD OPTICAL ELECTRONICS (THAILAND) CO.,LTD.',
                'name_tbt' => 'JVCKENWOOD OPTICAL ELECTRONICS (THAILAND) CO.,LTD.',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'customer_code' => 'BOI0007',
                'name_ic' => 'JANOME (THAILAND) COMPANY LIMITED',
                'name_tbt' => 'JANOME (THAILAND) CO.,LTD.',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'customer_code' => 'BOI0208',
                'name_ic' => 'HUDSON MANUFACTURE (THAILAND) CO.,LTD.',
                'name_tbt' => 'HUDSON MANUFACTURE (THAILAND) CO.,LTD',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'customer_code' => 'BOI0196',
                'name_ic' => 'NEC PLATFORMS THAI COMPANY LIMITED',
                'name_tbt' => 'NEC PLATFORMS THAI CO. LTD. HEAD OFFICE',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'customer_code' => 'BOI0048',
                'name_ic' => 'THAI SOHBI KOHGEI CO.,LTD.',
                'name_tbt' => 'THAI SOHBI KOHGEI CO.,LTD.',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'customer_code' => 'BOI0164',
                'name_ic' => 'NIHON F.T.B.(THAILAND) CO.,LTD.',
                'name_tbt' => 'NIHON F.T.B.(THAILAND) CO., LTD.  ',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'customer_code' => 'BOI0080',
                'name_ic' => 'SHARP MANUFACTURING (THAILAND) COMPANY LIMITED',
                'name_tbt' => 'SHARP MANUFACTURING (THAILAND) CO.,LTD.',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'customer_code' => 'BOI0198',
                'name_ic' => 'UMC ELECTRONICS (THAILAND) LIMITED',
                'name_tbt' => 'UMC ELECTRONICS (THAILAND) LIMITED',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'customer_code' => 'BOI0166',
                'name_ic' => 'FTE PRECISION (THAILAND) COMPANY LIMITED',
                'name_tbt' => 'FTE PRECISION (THAILAND) CO., LTD.',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'customer_code' => 'BOI0212',
                'name_ic' => 'TS MOLYMER CO.,LTD',
                'name_tbt' => 'TS MOLYMER CO.,LTD.',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'customer_code' => 'BOI0186',
                'name_ic' => 'TAPACO PUBLIC COMPANY LIMITED',
                'name_tbt' => 'TAPACO PUBLIC COMPANY LIMITED',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'customer_code' => 'BOI0023',
                'name_ic' => 'SUMITRONICS (THAILAND) CO.,LTD.',
                'name_tbt' => 'SUMITRONICS (THAILAND) CO.,LTD.',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'customer_code' => 'BOI0075',
                'name_ic' => 'PIONEER MANUFACTURING (THAILAND) COMPANY LIMITED',
                'name_tbt' => 'PIONEER MANUFACTURING (THAILAND) CO.,LTD.',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'customer_code' => 'BOI0168',
                'name_ic' => 'VALEO COMFORT AND DRIVING ASSISTANCE SYSTEMS (THAILAND) LIMITED',
                'name_tbt' => 'VALEO COMFORT AND DRIVING ASSISTANCE SYSTEMS',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'customer_code' => 'BOI0149',
                'name_ic' => 'CANON PRACHINBURI (THAILAND) LIMITED',
                'name_tbt' => 'CANON PRACHINBURI (THAILAND) LTD.',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'customer_code' => 'BOI9009',
                'name_ic' => 'CASIO (THAILAND) COMPANY LIMITED',
                'name_tbt' => 'CASIO (THAILAND) CO.,LTD. BRANCH 00002',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'customer_code' => 'BOI0159',
                'name_ic' => 'SINFONIA TECHNOLOGY (THAILAND) CO.,LTD.',
                'name_tbt' => 'SINFONIA TECHNOLOGY (THAILAND) CO., LTD.',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'customer_code' => 'BOI9000',
                'name_ic' => 'CANON HI-TECH (THAILAND) COMPANY LIMITED',
                'name_tbt' => 'CANON HI-TECH (THAILAND) LTD.',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'customer_code' => 'BOI0020',
                'name_ic' => 'TOSHIBA CARRIER (THAILAND) CO.,LTD.',
                'name_tbt' => 'TOSHIBA CARRIER (THAILAND) CO.,LTD(TCTC)',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'customer_code' => 'BOI0150',
                'name_ic' => 'MITSUWA CHEMICAL (THAILAND) COMPANY LIMITED',
                'name_tbt' => 'MITSUWA CHEMICAL (THAILAND) CO., LTD.',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'customer_code' => 'BOI9002',
                'name_ic' => 'NK MECHATRONICS CO.,LTD.',
                'name_tbt' => 'NK MECHATRONICS CO.,LTD.',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'customer_code' => 'BOI0206',
                'name_ic' => 'THAI SANKO COMPANY LIMITED',
                'name_tbt' => 'THAI SANKO CO., LTD.',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'customer_code' => 'BOI0200',
                'name_ic' => 'SUNNINGDALE TECH (THAILAND) COMPANY LIMITED',
                'name_tbt' => 'SUNNINGDALE TECH (THAILAND) CO., LTD.',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'customer_code' => 'BOI0056',
                'name_ic' => 'THAI TECH MATSUDA COMPANY LIMITED',
                'name_tbt' => 'THAI TECH MATSUDA CO.,LTD.  HEAD OFFICE',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'customer_code' => 'BOI0078',
                'name_ic' => 'MIC INDUSTRIES (THAILAND) CO.,LTD.',
                'name_tbt' => 'MIC INDUSTRIES (THAILAND) CO., LTD.',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'customer_code' => 'BOI0129',
                'name_ic' => 'NITTO KOHKI INDUSTRY(THAILAND)CO.,LTD',
                'name_tbt' => 'NITTO KOHKI INDUSTRY (THAILAND) CO.,LTD.',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'customer_code' => 'BOI0024',
                'name_ic' => 'THAI INOAC COMPONENTS COMPANY LIMITED',
                'name_tbt' => 'THAI INOAC COMPONENTS CO.,LTD.',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'customer_code' => 'BOI0126',
                'name_ic' => 'RICOH MANUFACTURING (THAILAND) CO.,LTD',
                'name_tbt' => 'RICOH MANUFACTURING (THAILAND) LTD',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'customer_code' => 'BOI0195',
                'name_ic' => 'CHEUNG SHING PRECISION INDUSTRY (THAILAND) COMPANY LIMITED',
                'name_tbt' => 'CHEUNG SHING PRECISION INDUSTRY(THAILAND) CO.,LTD.',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'customer_code' => 'BOI0179',
                'name_ic' => 'HARACHU (THAILAND) COMPANY LIMITED',
                'name_tbt' => 'HARACHU (THAILAND) CO.,LTD.',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'customer_code' => 'BOI9003',
                'name_ic' => 'KORAT MATSUSHITA CO.,LTD.',
                'name_tbt' => 'KORAT MATSUSHITA CO.,LTD.',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'customer_code' => 'BOI0135',
                'name_ic' => 'FTN (SARABURI) COMPANY LIMITED',
                'name_tbt' => 'FTN (SARABURI) CO.,LTD.',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'customer_code' => 'BOI0167',
                'name_ic' => 'TAIYO MANUFACTURING (THAILAND) COMPANY LIMITED',
                'name_tbt' => 'TAIYO MANUFACTURING (THAILAND) CO.,LTD',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'customer_code' => 'BOI0136',
                'name_ic' => 'SIAM NSK STEERING SYSTEMS CO.,LTD.',
                'name_tbt' => 'SIAM NSK STEERING SYSTEMS CO.,LTD.',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'customer_code' => 'BOI0053',
                'name_ic' => 'THAI STARLITE MANUFACTURING COMPANY LIMITED',
                'name_tbt' => 'THAI STARLITE MANUFACTURING CO., LTD',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'customer_code' => 'BOI0172',
                'name_ic' => 'NITTA M&T (THAILAND) COMPANY LIMITED',
                'name_tbt' => 'NITTA M&T (THAILAND) CO.,LTD',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'customer_code' => 'BOI0197',
                'name_ic' => 'MUTO (THAILAND) COMPANY LIMITED',
                'name_tbt' => 'MUTO (THAILAND) CO., LTD.',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'customer_code' => 'BOI0169',
                'name_ic' => 'NOBLE TRADING BANGKOK COMPANY LIMITED',
                'name_tbt' => 'NOBLE TRADING BANGKOK CO.,LTD.',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'customer_code' => 'BOI0010',
                'name_ic' => 'NIDEC PRECISION COMPONENTS (THAILAND) COMPANY LIMITED',
                'name_tbt' => 'NIDEC PRECISION COMPONENTS (THAILAND) CO.,LTD.',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'customer_code' => 'BOI0163',
                'name_ic' => 'HITACHI ASTEMO CHONBURI AUTO PARTS LIMITED',
                'name_tbt' => 'HITACHI ASTEMO CHONBURI AUTO PARTS LTD.',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'customer_code' => 'BOI0064',
                'name_ic' => 'TAPACO PUBLIC COMPANY LIMITED',
                'name_tbt' => 'TAPACO PUBLIC CO., LTD.',
                'is_use' => 1,
                'create_by' => 'admin',
            ],          
            [
                'customer_code' => 'BOI0116',
                'name_ic' => 'PRESS CRAFT (THAILAND) CO.,LTD.',
                'name_tbt' => 'PRESS CRAFT (THAILAND) CO., LTD.',
                'is_use' => 1,
                'create_by' => 'admin',
            ],   
            [
                'customer_code' => 'BOI0209',
                'name_ic' => 'ALPINE TECHNOLOGY MANUFACTURING (THAILAND) COMPANY LIMITED',
                'name_tbt' => 'ALPINE TECHNOLOGY MANUFACTURING ',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'customer_code' => 'BOI0131',
                'name_ic' => 'SEKISUI POLYMATECH (THAILAND) COMPANY LIMITED',
                'name_tbt' => 'SEKISUI POLYMATECH (THAILAND) CO., LTD',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'customer_code' => 'BOI0215',
                'name_ic' => 'THAI DIAMOND&ZEBRA ELECTRIC COMPANY LIMITED',
                'name_tbt' => 'THAI DIAMOND&ZEBRA ELECTRIC CO.,LTD.',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'customer_code' => 'BOI0107',
                'name_ic' => 'NIHON SEIKI THAI LIMITED',
                'name_tbt' => 'NIHON SEIKI THAI LIMITED',
                'is_use' => 1,
                'create_by' => 'admin',
            ],  
            [
                'customer_code' => 'BOI0174',
                'name_ic' => 'THERMODISC (THAILAND) LIMITED',
                'name_tbt' => 'THERMODISC (THAILAND) LIMITED',
                'is_use' => 1,
                'create_by' => 'admin',
            ],   
            [
                'customer_code' => 'BOI0052',
                'name_ic' => 'CARTON OPTICAL (SIAM) CO.,LTD.',
                'name_tbt' => 'CARTON OPTICAL (SIAM) CO., LTD. HEAD OFFICE',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'customer_code' => 'BOI0032',
                'name_ic' => 'NMB-MINEBEA THAI LIMITED',
                'name_tbt' => 'NMB-MINEBEA THAI LTD.',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'customer_code' => 'BOI0063',
                'name_ic' => 'NMB-MINEBEA THAI LIMITED',
                'name_tbt' => 'NMB-Minebea Thai Ltd.',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'customer_code' => 'BOI0066',
                'name_ic' => 'NMB-MINEBEA THAI LIMITED',
                'name_tbt' => 'NMB-MINEBEA THAI LTD.',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'customer_code' => 'BOI0113',
                'name_ic' => 'NMB-MINEBEA THAI LIMITED',
                'name_tbt' => 'NMB-Minebea Thai Ltd.  HEAD OFFICE',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            [
                'customer_code' => 'BOI0145',
                'name_ic' => 'NMB-MINEBEA THAI LIMITED',
                'name_tbt' => 'NMB-Minebea Thai Ltd. BRANCH 00004',
                'is_use' => 1,
                'create_by' => 'admin',
            ],
            
            // Add more sets of data as needed
        ];

        $this->db->table('mastertbt_customer')->insertBatch($data);
    }
}
